name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/ChiselRV32/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - uses: extractions/setup-just@v3

      - uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.12.5 # Specify the default Mill version
      # - uses: jodersky/setup-mill@master
      # - name: Setup Dependencies
      #   run: |
      #     sudo apt-get install ccache
      # - name: Get Cached Verilator
      #   id: get-cached-verilator
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.verilator-install-dir }}
      #     key: verilator-${{ env.verilator-version }}
      # - name: Install Verilator
      #   if: steps.get-cached-verilator.outputs.cache-hit != 'true'
      #   run: |
      #     sudo apt-get install git help2man perl python3 make autoconf g++ flex bison numactl perl-doc libfl-dev
      #     git clone https://github.com/verilator/verilator
      #     unset VERILATOR_ROOT
      #     cd verilator
      #     git checkout ${{ env.verilator-version  }}
      #     autoconf
      #     ./configure --prefix=$(pwd)/../${{ env.verilator-install-dir }}
      #     make
      #     make install
      # - name: Set PATH
      #   run: |
      #     echo "$(pwd)/${{ env.verilator-install-dir }}/bin" >> $GITHUB_PATH
      #     echo VERILATOR_ROOT="$(pwd)/${{ env.verilator-install-dir }}/share/verilator" >> $GITHUB_ENV
      #     ln -sf $(pwd)/${{ env.verilator-install-dir }}/bin/verilator_bin $(pwd)/${{ env.verilator-install-dir }}/share/verilator/verilator_bin
      - uses: veryl-lang/setup-verilator@v1
      # - name: SBT Test
      #   run: sbt test
      - name: mill Test run
        run: mill _.test

      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: imports.typ
      - run: typst compile spec.typ spec.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: spec.pdf
          path: spec.pdf
      # - name: Typst
      #   uses: lvignoli/typst-action@main
      #   with:
      #     source_file: spec.typ
