name: Continuous Integration

on:
  push:
    paths:
      - src/**
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/ChiselRV32/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - uses: extractions/setup-just@v3

      - uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.12.5 # Specify the default Mill version
      - uses: veryl-lang/setup-verilator@v1
      # - name: SBT Test
      #   run: sbt test
      - name: mill Test run
        run: mill _.test
      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: doc/imports.typ
      - run: just spec
      - uses: actions/upload-artifact@v4
        with:
          name: spec.pdf
          path: doc/spec.pdf
      # - name: Typst
      #   uses: lvignoli/typst-action@main
      #   with:
      #     source_file: spec.typ
